{% set name = "py_stringmatching" %}
{% set version = "0.4.5" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/{{ name }}/py-stringmatching-{{ version }}.tar.gz
  sha256: d97ba1b562ad98effc946687c5dab074c17a515114ab0dcf502202d5cec9f2b5

build:
  number: 0
  #skip: true  # [not x86_64]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - {{ compiler('c') }}
    - msinttypes  # [win and vc<14]
  host:
    - python
    - pip
    - setuptools
    - wheel
    - cython
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  source_files:
    - py_stringmatching/tests
  imports:
    - py_stringmatching
    - py_stringmatching.similarity_measure
    - py_stringmatching.tests
    - py_stringmatching.tokenizer
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - pytest -v py_stringmatching/tests

about:
  home: https://sites.google.com/site/anhaidgroup/current-projects/magellan/py_stringmatching
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python library for string matching.
  description: |
    This project seeks to build a Python software package that
    consists of a comprehensive and scalable set of string tokenizers
    (such as alphabetical tokenizers, whitespace tokenizers) and
    string similarity measures (such as edit distance, Jaccard,
    TF/IDF).
  doc_url: https://anhaidgroup.github.io/py_stringmatching/
  dev_url: https://github.com/anhaidgroup/py_stringmatching

extra:
  recipe-maintainers:
    - pjmartinkus
