# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_python2.7
    - CONFIG=osx_python3.6

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "dQ/WkZW+cbacnNeZoizIz1AaNX3JYDXZBFa6vlVcigZh8AmUeu7gRb4LKzGBC/3pNfLUgYi7LdXf8lP3NKkjAULIMM61TjIkuhFF1JHseBN4G0Cstvhlql0MlnYLq828HC4DnaAce2INTZYillpPfLWUeRWQuuqxcT83M1eu0hc5F0vEGFwYo+p+ji47cvH20/lL/uBmFB+VQoFe7mkWpBbL/nsBV5R3jfSdVKkdbsMa49mOthKiMqT12PuKuiuS0Ddk6U2ZNpyU7awgkAsvMc7HCzWfMH+H96JI9NzgyaB6MAMxUs39W64DH1r9POCMxCsNUC0FwhvAz3QjlxonKb2yA1YQdURW2g7Bo4e6PLHucaKRaYbBaFQ24o36Id1KnkP607K78BGBgrn5rGwEvaPYWw4b4fM87GA6opMTmoDkYuId8WEY0ecmk1xNL/euisEQIqgq/urRLTDrejXjdtutsetn615gjRkBORJ4CM5IaAk0H1lny2yM7/AlrkXUoLPjP1vkiUbprbbOMJPJ6TwGQbJWFh+4+XCduSFd/3VXlcDtRoWWzdd30xd5wI3HeK2osO4IO0xEu0prWfyS2ablZNRPrnfbGsecwmovVHWTs9d+YL5vCbh0nsVyK6o0WARZ/G/uvNbMgnouVv+HGHWpTQTLr5ASnSPGp/RnMrs="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2 conda-build
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  -  conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml