travis:
  secure:
    BINSTAR_TOKEN: Hc7JjpIhB5bqIu0JYn81Qcsc73KshrGX7YfXEL/ZmTp5ureffgGQuhEFd36NLcfmxoMmTmUFygT3ovAvLcVkf4pt0kMqITD3oU5JOsXV2ieLJJWLl2uD9XtC0I3uE/YGTeZWXcFcQQdq8FC4UcK2/M/l30zT5ZE2Rsu2T8GrLtgfC6197mU3KON85StlWbESmEYxn6Ze4LyAkT3e/uc8fHvuSdW5n4IObAR33OWKAOvwb5rdT6BHW+Y2gbso0xxYPVFHIPhN95XT4LMYqHhdsgL7ulhXNxpm4zt6gZJ53fXEnk0e5km8y6n1XNEx7sKlsfGigSsZJCc5YcpUAB8UIaC9Ysrp09xde9qHmepIUkbYXedly+Iny8bGiCjZhpn5sC28Y6aI6UJaxgQkXqt/s+avAD4AQRW0UYD2e8jDxURpSR0fH0jIsFoODeKLPhxY+I+AR2t/VYHnHdEHVaD+LvPtoskUvx4X2fbap+Qma/yzP+1BBRj90s4k7zvktdICFYEF096HuIOK5A0An1YmcN5CvRTXlTt25/bS42Gfm1fun34soNDV3QaKrFqVnn/krmwv7K4OplnIAQ5upZVYcgzlBifS1LccpW+om12cKNJZH1eZTk4ftW2910yZIrtaalNIkw4e+CzC54649j7CQswWIiTOSbI1aaJZ9nJIH44=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
